# Права:
# core.creativecontrol.bypass - Обход ограничений на креатив
# core.blackcommand.bypass - Обход запрещенных команд
#


Locations:
  Spawn: null

Function:
  CreativeControlBlocks: true # Блокировка взаимодействия игрока с блоками в креативе
  CreativeControlCommand: true # Блокировка взаимодействия игрока с командам в креативе
  BlackListCommand: true # Блокировка команд для игроков
  PutBlocks: true # Блокировка подбирания блоков, когда игрок в креативе
  DropBlocks: true # Блокировка выбрасывания блоков, когда игрок в креативе

WhiteListBlocks: # Черный список блоков, с которыми нельзя взаимодействовать в креативе
  - DIRT
  - CHEST
  -
CreativeWhiteList: # Черный список блоков, с которыми нельзя брать в креативе
  - STONE

BlackListCreativeCommands: # Черный список команд, с которыми нельзя взаимодействовать в креативе
  - ec
  - pizda

BlackListCommand: # Черный список команд
  - test

Messages:
  commandOnlyForPlayers: '&cКоманду можно использовать только от имени игрока.'
  noPermissions: '&7[&6&lСЕРВЕР&7] &fУ вас недостаточно прав.'
  spawnTeleport: '&7[&6&lСЕРВЕР&7] &fВы были телепортированы на спавн.'
  setSpawn: '&7[&6&lСЕРВЕР&7] &fВы установили точку спавна.'
  creativeControlCommand: '&7[&6&lСЕРВЕР&7] &fОтключите режим креатива для использования команд.'
  creativeControlBlocks: '&7[&6&lСЕРВЕР&7] &fОтключите режим креатива для взаимодействия с блоками.'
  blockCommand: '&7[&6&lСЕРВЕР&7] &fКоманда запрещена на сервере.'
  blackblock: '&7[&6&lСЕРВЕР&7] &fЭтот блок нельзя брать в креативе.'
  dropBlocks: '&7[&6&lСЕРВЕР&7] &fВыключите режим креатива для того, чтобы выбрасывать блоки.'
  putBlocks: '&7[&6&lСЕРВЕР&7] &fВыключите режим креатива, чтобы подобрать блок.'